### ISSUE TITLE
speed up the kernel images download

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#3005]
**Is your feature request related to a problem? Please describe.**
It takes a long time for the kernel images to get downloaded. Annoying for personal use and CI can take a long time as well.

**Describe the solution you'd like**
1. Multiple kernel images should be downloaded in parallel
2. Download compressed versions and unpack

**Comment by jxuanli** [comment]
ideally maybe we could cache the files (e.g. if we have a dedicated machine, just store the images without needing to download them each time) and only download new added or changed images

**Comment by patryk4815** [comment]
I think they are cached under our CI:
```
    - name: Set up cache for QEMU images
      if: matrix.type == 'qemu-system-tests'
      id: qemu-cache
      uses: actions/cache@v3
      with:
        path: ./tests/qemu-tests/images
        key: ${{ matrix.os }}-cache-qemu-images

```
